//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadBee.Core.MyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BadBee.Core.MyResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string account_settings {
            get {
                return ResourceManager.GetString("account_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new photo.
        /// </summary>
        public static string add_new_photo {
            get {
                return ResourceManager.GetString("add_new_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photo.
        /// </summary>
        public static string add_photo {
            get {
                return ResourceManager.GetString("add_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        public static string add_product {
            get {
                return ResourceManager.GetString("add_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string application {
            get {
                return ResourceManager.GetString("application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a search filter to see results.
        /// </summary>
        public static string applyfil {
            get {
                return ResourceManager.GetString("applyfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis.
        /// </summary>
        public static string axis {
            get {
                return ResourceManager.GetString("axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to table.
        /// </summary>
        public static string back_to_indicators {
            get {
                return ResourceManager.GetString("back_to_indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string back_to_list {
            get {
                return ResourceManager.GetString("back_to_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base serie.
        /// </summary>
        public static string baseserie {
            get {
                return ResourceManager.GetString("baseserie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brake lining.
        /// </summary>
        public static string brake_lining {
            get {
                return ResourceManager.GetString("brake_lining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brake pad.
        /// </summary>
        public static string brake_pad {
            get {
                return ResourceManager.GetString("brake_pad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brake system.
        /// </summary>
        public static string brakesystem {
            get {
                return ResourceManager.GetString("brakesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string brand {
            get {
                return ResourceManager.GetString("brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        public static string career {
            get {
                return ResourceManager.GetString("career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catalogue.
        /// </summary>
        public static string catalog {
            get {
                return ResourceManager.GetString("catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BadBee Catalogue.
        /// </summary>
        public static string catalog_title {
            get {
                return ResourceManager.GetString("catalog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATALOGUE OF BRAKE LININGS AND BRAKE PADS FOR COMMERCIAL VEHICLES.
        /// </summary>
        public static string catalog_title_cv {
            get {
                return ResourceManager.GetString("catalog_title_cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string change_password_button {
            get {
                return ResourceManager.GetString("change_password_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose BadBee No for product.
        /// </summary>
        public static string choose_BadBee {
            get {
                return ResourceManager.GetString("choose_BadBee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose name of product.
        /// </summary>
        public static string choose_name {
            get {
                return ResourceManager.GetString("choose_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose type of photo.
        /// </summary>
        public static string choose_type {
            get {
                return ResourceManager.GetString("choose_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose WVA number for product.
        /// </summary>
        public static string choose_wva {
            get {
                return ResourceManager.GetString("choose_wva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose brand .
        /// </summary>
        public static string choosebrand {
            get {
                return ResourceManager.GetString("choosebrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose model .
        /// </summary>
        public static string choosemodel {
            get {
                return ResourceManager.GetString("choosemodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose serie .
        /// </summary>
        public static string chooseserie {
            get {
                return ResourceManager.GetString("chooseserie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean filters.
        /// </summary>
        public static string cleanFilters {
            get {
                return ResourceManager.GetString("cleanFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaboration with FEMFM and TUV.
        /// </summary>
        public static string coll {
            get {
                return ResourceManager.GetString("coll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        public static string collandcareer {
            get {
                return ResourceManager.GetString("collandcareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string confirm_password {
            get {
                return ResourceManager.GetString("confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string create_a_new_account {
            get {
                return ResourceManager.GetString("create_a_new_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new cross.
        /// </summary>
        public static string create_new_cross {
            get {
                return ResourceManager.GetString("create_new_cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new product.
        /// </summary>
        public static string create_new_prod {
            get {
                return ResourceManager.GetString("create_new_prod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        public static string create_user {
            get {
                return ResourceManager.GetString("create_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number from another manufacturer.
        /// </summary>
        public static string cross {
            get {
                return ResourceManager.GetString("cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross brand name.
        /// </summary>
        public static string cross_brand_name {
            get {
                return ResourceManager.GetString("cross_brand_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross brand number.
        /// </summary>
        public static string cross_brand_number {
            get {
                return ResourceManager.GetString("cross_brand_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross number.
        /// </summary>
        public static string cross_number {
            get {
                return ResourceManager.GetString("cross_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosses.
        /// </summary>
        public static string crosses {
            get {
                return ResourceManager.GetString("crosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSR.
        /// </summary>
        public static string csr {
            get {
                return ResourceManager.GetString("csr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently there are.
        /// </summary>
        public static string currently {
            get {
                return ResourceManager.GetString("currently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer service Department.
        /// </summary>
        public static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        public static string date_from {
            get {
                return ResourceManager.GetString("date_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from (DD-MM-YYYY).
        /// </summary>
        public static string date_from_format {
            get {
                return ResourceManager.GetString("date_from_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To.
        /// </summary>
        public static string date_to {
            get {
                return ResourceManager.GetString("date_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to (DD-MM-YYYY).
        /// </summary>
        public static string date_to_format {
            get {
                return ResourceManager.GetString("date_to_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string delete_confirm {
            get {
                return ResourceManager.GetString("delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design and execution by.
        /// </summary>
        public static string design_execution_by {
            get {
                return ResourceManager.GetString("design_execution_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⌀.
        /// </summary>
        public static string diameter {
            get {
                return ResourceManager.GetString("diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string dimensions {
            get {
                return ResourceManager.GetString("dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc.
        /// </summary>
        public static string disc {
            get {
                return ResourceManager.GetString("disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc No.
        /// </summary>
        public static string disc_no {
            get {
                return ResourceManager.GetString("disc_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download application for Android.
        /// </summary>
        public static string download_for_android {
            get {
                return ResourceManager.GetString("download_for_android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download application for  iOS.
        /// </summary>
        public static string download_for_ios {
            get {
                return ResourceManager.GetString("download_for_ios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download application for Windows Phone.
        /// </summary>
        public static string download_for_wp {
            get {
                return ResourceManager.GetString("download_for_wp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export crosses to XLS.
        /// </summary>
        public static string download_xls_cross {
            get {
                return ResourceManager.GetString("download_xls_cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export products data to XLS.
        /// </summary>
        public static string download_xls_products {
            get {
                return ResourceManager.GetString("download_xls_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the PDF Catalogue.
        /// </summary>
        public static string downloadpdf {
            get {
                return ResourceManager.GetString("downloadpdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum diameter.
        /// </summary>
        public static string drumdiameter {
            get {
                return ResourceManager.GetString("drumdiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum diameter.
        /// </summary>
        public static string drumdiameter1 {
            get {
                return ResourceManager.GetString("drumdiameter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string enter_brand {
            get {
                return ResourceManager.GetString("enter_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string enter_diameter {
            get {
                return ResourceManager.GetString("enter_diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter filter.
        /// </summary>
        public static string enter_filter {
            get {
                return ResourceManager.GetString("enter_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string enter_height {
            get {
                return ResourceManager.GetString("enter_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string enter_model {
            get {
                return ResourceManager.GetString("enter_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivets.
        /// </summary>
        public static string enter_rivets {
            get {
                return ResourceManager.GetString("enter_rivets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string enter_serie {
            get {
                return ResourceManager.GetString("enter_serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number from another system here.
        /// </summary>
        public static string enter_text_search {
            get {
                return ResourceManager.GetString("enter_text_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WVA.
        /// </summary>
        public static string enter_wva {
            get {
                return ResourceManager.GetString("enter_wva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string enter_year {
            get {
                return ResourceManager.GetString("enter_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EU funds.
        /// </summary>
        public static string eu {
            get {
                return ResourceManager.GetString("eu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        public static string exportToCSV {
            get {
                return ResourceManager.GetString("exportToCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by.
        /// </summary>
        public static string filterby {
            get {
                return ResourceManager.GetString("filterby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        public static string front {
            get {
                return ResourceManager.GetString("front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F/R.
        /// </summary>
        public static string front_rear {
            get {
                return ResourceManager.GetString("front_rear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to list of pictures.
        /// </summary>
        public static string go_to_list {
            get {
                return ResourceManager.GetString("go_to_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to website.
        /// </summary>
        public static string go_website {
            get {
                return ResourceManager.GetString("go_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string goback {
            get {
                return ResourceManager.GetString("goback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items in the database..
        /// </summary>
        public static string indb {
            get {
                return ResourceManager.GetString("indb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicators.
        /// </summary>
        public static string indicators {
            get {
                return ResourceManager.GetString("indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoe.
        /// </summary>
        public static string jaw {
            get {
                return ResourceManager.GetString("jaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM.
        /// </summary>
        public static string km {
            get {
                return ResourceManager.GetString("km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KW.
        /// </summary>
        public static string kw {
            get {
                return ResourceManager.GetString("kw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length [mm].
        /// </summary>
        public static string length {
            get {
                return ResourceManager.GetString("length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of pictures.
        /// </summary>
        public static string list_of_pictures {
            get {
                return ResourceManager.GetString("list_of_pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string log_in {
            get {
                return ResourceManager.GetString("log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string log_in_btn {
            get {
                return ResourceManager.GetString("log_in_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BadBee No..
        /// </summary>
        public static string BadBee_no {
            get {
                return ResourceManager.GetString("BadBee_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management methods.
        /// </summary>
        public static string methods {
            get {
                return ResourceManager.GetString("methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online catalogs available in your phone.
        /// </summary>
        public static string mobile_catalog {
            get {
                return ResourceManager.GetString("mobile_catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to search in list.
        /// </summary>
        public static string modalsearch {
            get {
                return ResourceManager.GetString("modalsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Mounting kit 01TK540001 must be installed.
        /// </summary>
        public static string mounting_kit_instruction {
            get {
                return ResourceManager.GetString("mounting_kit_instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no PDF yet..
        /// </summary>
        public static string nopdf {
            get {
                return ResourceManager.GetString("nopdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found in the database..
        /// </summary>
        public static string noRecordsFound {
            get {
                return ResourceManager.GetString("noRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OE.
        /// </summary>
        public static string oe {
            get {
                return ResourceManager.GetString("oe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string offer {
            get {
                return ResourceManager.GetString("offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string office {
            get {
                return ResourceManager.GetString("office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old passowrd.
        /// </summary>
        public static string old_password {
            get {
                return ResourceManager.GetString("old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our products.
        /// </summary>
        public static string ourprod {
            get {
                return ResourceManager.GetString("ourprod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad.
        /// </summary>
        public static string pad {
            get {
                return ResourceManager.GetString("pad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad No.
        /// </summary>
        public static string pad_no {
            get {
                return ResourceManager.GetString("pad_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string passwords_do_not_match {
            get {
                return ResourceManager.GetString("passwords_do_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo of components (choose BadBee No.).
        /// </summary>
        public static string photo_of_components {
            get {
                return ResourceManager.GetString("photo_of_components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo of components and kit (choose BadBee No.).
        /// </summary>
        public static string photo_of_kit {
            get {
                return ResourceManager.GetString("photo_of_kit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture of components.
        /// </summary>
        public static string pict_of_components {
            get {
                return ResourceManager.GetString("pict_of_components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture of component with box.
        /// </summary>
        public static string pict_of_components_with_box {
            get {
                return ResourceManager.GetString("pict_of_components_with_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string pictures {
            get {
                return ResourceManager.GetString("pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        public static string poland {
            get {
                return ResourceManager.GetString("poland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string power {
            get {
                return ResourceManager.GetString("power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        public static string product_name {
            get {
                return ResourceManager.GetString("product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string qtt {
            get {
                return ResourceManager.GetString("qtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity in kit.
        /// </summary>
        public static string qtt_in_kit {
            get {
                return ResourceManager.GetString("qtt_in_kit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product quality.
        /// </summary>
        public static string qualityprod {
            get {
                return ResourceManager.GetString("qualityprod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range of operations.
        /// </summary>
        public static string range {
            get {
                return ResourceManager.GetString("range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear.
        /// </summary>
        public static string rear {
            get {
                return ResourceManager.GetString("rear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main reception.
        /// </summary>
        public static string reception {
            get {
                return ResourceManager.GetString("reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register_btn {
            get {
                return ResourceManager.GetString("register_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string remember_me {
            get {
                return ResourceManager.GetString("remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivets.
        /// </summary>
        public static string rivets {
            get {
                return ResourceManager.GetString("rivets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivets quantity.
        /// </summary>
        public static string rivets_qtt {
            get {
                return ResourceManager.GetString("rivets_qtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivets quantity for product.
        /// </summary>
        public static string rivets_qtt_for_product {
            get {
                return ResourceManager.GetString("rivets_qtt_for_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivets quantity in kit.
        /// </summary>
        public static string rivets_qtt_in_kit {
            get {
                return ResourceManager.GetString("rivets_qtt_in_kit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivets total.
        /// </summary>
        public static string rivets_total {
            get {
                return ResourceManager.GetString("rivets_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        public static string schema {
            get {
                return ResourceManager.GetString("schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema (choose BadBee No.).
        /// </summary>
        public static string schema_BadBee {
            get {
                return ResourceManager.GetString("schema_BadBee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema (choose WVA number).
        /// </summary>
        public static string schema_wva {
            get {
                return ResourceManager.GetString("schema_wva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter BadBee number / cross.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by application.
        /// </summary>
        public static string searchapp {
            get {
                return ResourceManager.GetString("searchapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string searchbtn {
            get {
                return ResourceManager.GetString("searchbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross reference search.
        /// </summary>
        public static string searchByCrosses {
            get {
                return ResourceManager.GetString("searchByCrosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by details.
        /// </summary>
        public static string searchdet {
            get {
                return ResourceManager.GetString("searchdet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching.
        /// </summary>
        public static string searching {
            get {
                return ResourceManager.GetString("searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string serie {
            get {
                return ResourceManager.GetString("serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set No.
        /// </summary>
        public static string set_no {
            get {
                return ResourceManager.GetString("set_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke.
        /// </summary>
        public static string stroke {
            get {
                return ResourceManager.GetString("stroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string supp {
            get {
                return ResourceManager.GetString("supp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string t {
            get {
                return ResourceManager.GetString("t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology and development.
        /// </summary>
        public static string tech {
            get {
                return ResourceManager.GetString("tech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        public static string thickness {
            get {
                return ResourceManager.GetString("thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAILER, SEMITRAILER.
        /// </summary>
        public static string trailer {
            get {
                return ResourceManager.GetString("trailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        public static string uk {
            get {
                return ResourceManager.GetString("uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAGE UP.
        /// </summary>
        public static string up {
            get {
                return ResourceManager.GetString("up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string use_account_to_log_in {
            get {
                return ResourceManager.GetString("use_account_to_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our values.
        /// </summary>
        public static string values {
            get {
                return ResourceManager.GetString("values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string w {
            get {
                return ResourceManager.GetString("w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string want_delete {
            get {
                return ResourceManager.GetString("want_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wear indicator for brake pad.
        /// </summary>
        public static string wear_indicator {
            get {
                return ResourceManager.GetString("wear_indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedge.
        /// </summary>
        public static string wedge {
            get {
                return ResourceManager.GetString("wedge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WVA.
        /// </summary>
        public static string wva {
            get {
                return ResourceManager.GetString("wva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WVA description.
        /// </summary>
        public static string wva_desc {
            get {
                return ResourceManager.GetString("wva_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WVA details.
        /// </summary>
        public static string wva_det {
            get {
                return ResourceManager.GetString("wva_det", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WVA details quantity.
        /// </summary>
        public static string wva_det_qty {
            get {
                return ResourceManager.GetString("wva_det_qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of production.
        /// </summary>
        public static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
    }
}
