//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lumag.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crosses
    {
        public string LumagNumber { get; set; }
        public string CrossBrandName { get; set; }
        public string CrossBrandNumber { get; set; }
        public int Id { get; set; }
        public Nullable<int> LumagNumberId { get; set; }
    }
}
