//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lumag.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsDb
    {
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Type { get; set; }
        public string Serie { get; set; }
        public string Model { get; set; }
        public string Kw { get; set; }
        public string Km { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string Fr { get; set; }
        public string WvaDesc { get; set; }
        public string Wva { get; set; }
        public string WvaDetailsQty { get; set; }
        public string WvaDetails { get; set; }
        public string LumagNumber { get; set; }
        public string Height { get; set; }
        public string Width { get; set; }
        public string Thickness { get; set; }
        public string Wedge { get; set; }
        public string DrumDiameter { get; set; }
        public string BrakeSystem { get; set; }
        public string RivetsQuantity { get; set; }
        public string RivetsType { get; set; }
        public string ProductType { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> SerieId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> WvaId { get; set; }
        public Nullable<int> WvaDetailsId { get; set; }
        public Nullable<int> LumagNumberId { get; set; }
        public Nullable<int> ThicknessId { get; set; }
        public Nullable<int> RivetTypeId { get; set; }
        public Nullable<int> WidthId { get; set; }
        public Nullable<int> HeightId { get; set; }
        public Nullable<int> SystemId { get; set; }
        public Nullable<int> DrumDiameterId { get; set; }
        public Nullable<int> PictureId { get; set; }
    }
}
