//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lumag.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pictures
    {
        public int Id { get; set; }
        public string LumagNo { get; set; }
        public string Schema1 { get; set; }
        public string Schema2 { get; set; }
        public string Picture1 { get; set; }
        public string Picture2 { get; set; }
    }
}
