//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lumag.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rivets
    {
        public int Id { get; set; }
        public string RivetName { get; set; }
        public string RivetType { get; set; }
        public string RivetDimensions { get; set; }
        public string RivetDimensionsSize { get; set; }
        public string RivetDimensionsDesc { get; set; }
        public string Quantity { get; set; }
    }
}
