//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadBeeCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class BadBee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BadBee()
        {
            this.Item = new HashSet<Item>();
        }
    
        public System.Guid BadBeeId { get; set; }
        public string BadBeeNo { get; set; }
        public Nullable<System.Guid> WvaId { get; set; }
        public Nullable<System.Guid> SystemId { get; set; }
        public Nullable<System.Guid> DimensionId { get; set; }
        public Nullable<System.Guid> RivetId { get; set; }
    
        public virtual Dimension Dimension { get; set; }
        public virtual Rivet Rivet { get; set; }
        public virtual System System { get; set; }
        public virtual Wva Wva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Item { get; set; }
    }
}
