//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadBeeCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ModelId { get; set; }
        public Nullable<System.Guid> BadBeeId { get; set; }
    
        public virtual BadBee BadBee { get; set; }
        public virtual Model Model { get; set; }
    }
}
